main: com.faiizer.skzen.SkZen
name: SkZen
version: '${project.version}'
description: "A simple Skript addon to help customize your server to the fullest."
api-version: '1.20'
author: Faiizer
website: https://github.com/Faiizer/SkZen
depend:
  - Skript